name: Get changed files for a pull request
description: Get all of the files changed in a pull request.
author: 'Andrey Larin <lestex@gmail.com>'
branding:
  icon: file
  color: purple
runs:
  using: node20
  main: dist/index.js
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
    required: true
    default: ${{ github.token }}
  repository:
    description: Github repository
    default: ${{ github.event.repository.name }}
    required: true
  owner:
    description: Github repository owner
    required: false
  pr-number:
    description: Pull request number
    required: true
    default: ${{ github.event.number }}
  per-page:
    description: Number of items per page in API call.
    required: true
    default: '100'
  result-encoding:
    description: Either "string" or "json" how the result will be encoded.
    default: json
outputs:
  files:
    description: >
      The list of files changed in a pull request.
  sha:
    description: >
      Most recent commit SHA in a pull request.
  msg:
    description: >
      Most recent commit message in a pull request.
