name: Get All Changed Files
description: Get all of the files changed/modified in a pull request or push's commits.
author: Priceline.com
branding:
  icon: file
  color: purple
runs:
  using: node16
  main: dist/index.js
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
    required: true
    default: ${{ github.token }}
  repository:
    description: Github repository
    default: ${{ github.event.repository.name }}
    required: true
  filter:
    description: File extentions to filter
    required: true
    default: 'yml,tf'
outputs:
  files:
    description: >
      The list of files changed in PR.
